# Churn Modeling Project (Dataset Upload + Setup)

## Aim
To upload a dataset into Google Colab and load it using Pandas for further analysis / ML.

## Tools Used
- Google Colab
- Python
- Pandas

In [5]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("himanshunakrani/iris-dataset")

print("Path to dataset files:", path)

import os
os.listdir("/kaggle/input/iris-dataset")

Using Colab cache for faster access to the 'iris-dataset' dataset.
Path to dataset files: /kaggle/input/iris-dataset

['iris.csv']

In [2]:
from google.colab import files
uploaded = files.upload()

Saving iris.csv to iris.csv

In [4]:
import pandas as pd
df = pd.read_csv("iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [6]:
import kagglehub
path = kagglehub.dataset_download("uciml/iris")

Using Colab cache for faster access to the 'iris' dataset.

## Step 1: Mount Google Drive
We mount Google Drive to access files stored in MyDrive.

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## Step 2: Locate Dataset File in Drive
Check if the dataset exists in MyDrive.

In [9]:
import os
os.listdir("/content/drive/MyDrive")

['Colab Notebooks',
 'PXL_20250217_055427684.MP.jpg',
 'PXL_20250217_055435726.jpg',
 '2 (1).jpg',
 '2.jpg',
 'Screenshot_20240917-163758.png',
 'Pranav Patel(19554) 1CSE22 .pdf',
 'IMG-20241011-WA0031.jpg',
 'Classroom',
 'IILM QuestionBank.gdoc',
 'photo_2024-12-12_16-07-02.jpg',
 'Screenshot_20250507_101916_Chrome.jpg',
 'Student_Cumulative_Marksheet_copy.pdf',
 'AY23-24-958170150562.pdf',
 'Supplementary_Examination_1st_Year_(2024-2025_batch)[1].csv',
 'IMG-20250707-WA0000.jpg',
 'IMG-20250707-WA0001.jpg',
 'Supplementary_Examination_1st_Year_(2024-2025_batch)[1].gsheet',
 '1000061481.png',
 'PRANAV_PATEL_2CSE22.pdf',
 'photo_2025-08-25_12-03-10.jpg',
 'Pranav.patel_2CS22.jpg',
 'PranavPatel_2_2CSE22_2410031387.pdf',
 'iris.csv']

## Step 3: Load CSV Dataset using Pandas
We load the dataset into a DataFrame for analysis.

In [10]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df.shape

(150, 5)

## Output
- Dataset successfully loaded
- First 5 rows displayed using `df.head()`
- Next step: data cleaning / model training

In [12]:
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [13]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')